// <auto-generated />
using System;
using DateFinder.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DateFinder.Storage.Migrations
{
    [DbContext(typeof(DateFinderDbContext))]
    [Migration("20240627230928_message")]
    partial class message
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DateFinder.Domain.Storage.Date", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivityLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Duration")
                        .HasColumnType("float");

                    b.Property<string>("IndoorOutdoor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rating")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bfc65bb0-2355-4223-b9b1-4a1e06a4e6c8"),
                            ActivityLevel = "High",
                            Duration = 4.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "rock climbing"
                        },
                        new
                        {
                            Id = new Guid("ad3d5f90-9e69-4080-b199-059e358c473f"),
                            ActivityLevel = "High",
                            Duration = 2.5,
                            IndoorOutdoor = "Indoor",
                            Name = "indoor rock climbing"
                        },
                        new
                        {
                            Id = new Guid("bd368050-308a-449d-8df6-42d585287dc9"),
                            ActivityLevel = "Medium",
                            Duration = 5.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "amusement park"
                        },
                        new
                        {
                            Id = new Guid("5c564aec-13e5-48e9-bc33-4a63a0799d8a"),
                            ActivityLevel = "Medium",
                            Duration = 2.0,
                            IndoorOutdoor = "Indoor",
                            Name = "bowling"
                        },
                        new
                        {
                            Id = new Guid("dd0772ae-a650-4c1b-b9b7-db8b511d3229"),
                            ActivityLevel = "Medium",
                            Duration = 2.0,
                            IndoorOutdoor = "Both",
                            Name = "mini golf"
                        },
                        new
                        {
                            Id = new Guid("86a17ebc-92b0-4913-9dd3-984d823c128c"),
                            ActivityLevel = "Medium",
                            Duration = 4.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "golf"
                        },
                        new
                        {
                            Id = new Guid("805eb25c-6e2e-45bb-9952-f41038737c1f"),
                            ActivityLevel = "Medium",
                            Duration = 2.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "driving range"
                        },
                        new
                        {
                            Id = new Guid("e3e3b06d-21ab-49dd-844a-0de1800700b6"),
                            ActivityLevel = "High",
                            Duration = 2.0,
                            IndoorOutdoor = "Indoor",
                            Name = "trampoline park"
                        },
                        new
                        {
                            Id = new Guid("d718e815-da67-4b4a-a0f5-dcf80632efbc"),
                            ActivityLevel = "Low",
                            Duration = 3.5,
                            IndoorOutdoor = "Both",
                            Name = "live music"
                        },
                        new
                        {
                            Id = new Guid("a9419870-c228-4e66-b7ad-c7d85c5041e7"),
                            ActivityLevel = "Medium",
                            Duration = 3.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "zoo"
                        },
                        new
                        {
                            Id = new Guid("9730ce3a-a838-4348-92cf-1921bae78cb6"),
                            ActivityLevel = "Medium",
                            Duration = 2.5,
                            IndoorOutdoor = "Both",
                            Name = "botanical garden"
                        },
                        new
                        {
                            Id = new Guid("c88cad38-382b-4bfb-9eb7-f804075105f7"),
                            ActivityLevel = "Medium",
                            Duration = 3.0,
                            IndoorOutdoor = "Indoor",
                            Name = "museum"
                        },
                        new
                        {
                            Id = new Guid("42f47a06-2557-4882-89ce-f14441aa0c6e"),
                            ActivityLevel = "Medium",
                            Duration = 2.5,
                            IndoorOutdoor = "Indoor",
                            Name = "art museum"
                        },
                        new
                        {
                            Id = new Guid("cf5cc53b-cdd6-4452-8f55-bcd45a213800"),
                            ActivityLevel = "Medium",
                            Duration = 2.0,
                            IndoorOutdoor = "Indoor",
                            Name = "mall"
                        },
                        new
                        {
                            Id = new Guid("52d63045-4a1e-4130-8edd-925bcad5fb0f"),
                            ActivityLevel = "Medium",
                            Duration = 1.5,
                            IndoorOutdoor = "Indoor",
                            Name = "laser tag"
                        },
                        new
                        {
                            Id = new Guid("d24047c3-0982-4f71-8999-0fff60cb748c"),
                            ActivityLevel = "High",
                            Duration = 2.5,
                            IndoorOutdoor = "Indoor",
                            Name = "indoor scuba diving"
                        },
                        new
                        {
                            Id = new Guid("0deaf8f8-818f-47b3-a357-0e02d7a1557a"),
                            ActivityLevel = "High",
                            Duration = 1.5,
                            IndoorOutdoor = "Indoor",
                            Name = "indoor skydiving"
                        },
                        new
                        {
                            Id = new Guid("cf096883-244e-4156-b05c-1a18c4d91fea"),
                            ActivityLevel = "Medium",
                            Duration = 2.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "ice castle"
                        },
                        new
                        {
                            Id = new Guid("86942b5b-33cd-40c7-8635-550c08284663"),
                            ActivityLevel = "Low",
                            Duration = 3.0,
                            IndoorOutdoor = "Indoor",
                            Name = "play/musical"
                        },
                        new
                        {
                            Id = new Guid("fc2a60a4-1927-4384-aaa8-50416d011f9a"),
                            ActivityLevel = "Medium",
                            Duration = 4.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "beach"
                        },
                        new
                        {
                            Id = new Guid("c4019fb0-6e8e-4f2c-bbec-3b36842dc2ae"),
                            ActivityLevel = "Medium",
                            Duration = 2.0,
                            IndoorOutdoor = "Indoor",
                            Name = "butterfly"
                        },
                        new
                        {
                            Id = new Guid("28d66744-a6e1-4967-90a8-343306ef91ed"),
                            ActivityLevel = "Low",
                            Duration = 1.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "farmers market"
                        },
                        new
                        {
                            Id = new Guid("3bc973f5-f9a0-4cc2-808f-9c9eac359db6"),
                            ActivityLevel = "Low",
                            Duration = 3.5,
                            IndoorOutdoor = "Indoor",
                            Name = "movie"
                        },
                        new
                        {
                            Id = new Guid("50cabfce-aced-4074-a61b-9a72f1fe7161"),
                            ActivityLevel = "Low",
                            Duration = 3.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "drive in movie"
                        },
                        new
                        {
                            Id = new Guid("c364471f-6bcb-4b92-86cd-ce94b98b000e"),
                            ActivityLevel = "Low",
                            Duration = 1.5,
                            IndoorOutdoor = "Indoor",
                            Name = "arcade"
                        },
                        new
                        {
                            Id = new Guid("bf2ba458-f787-4e56-93f5-84e9f40e1a92"),
                            ActivityLevel = "High",
                            Duration = 1.5,
                            IndoorOutdoor = "Both",
                            Name = "ice skating"
                        },
                        new
                        {
                            Id = new Guid("9fed3c73-618d-45db-9e26-68ec1373ea8d"),
                            ActivityLevel = "High",
                            Duration = 3.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "mountain biking"
                        },
                        new
                        {
                            Id = new Guid("a5e7df70-ca1f-451c-8ddc-4779adc26a95"),
                            ActivityLevel = "Medium",
                            Duration = 1.5,
                            IndoorOutdoor = "Indoor",
                            Name = "axe throwing"
                        },
                        new
                        {
                            Id = new Guid("de68b7be-3552-4b3b-b585-7bb00323a228"),
                            ActivityLevel = "Medium",
                            Duration = 1.5,
                            IndoorOutdoor = "Both",
                            Name = "archery"
                        },
                        new
                        {
                            Id = new Guid("c92edbe9-8efb-4b8b-96fc-fb7d92ea8fdb"),
                            ActivityLevel = "Low",
                            Duration = 1.0,
                            IndoorOutdoor = "Indoor",
                            Name = "boba"
                        },
                        new
                        {
                            Id = new Guid("b2d86f27-15fe-489e-80e4-9101ac6e59f5"),
                            ActivityLevel = "Low",
                            Duration = 1.0,
                            IndoorOutdoor = "Indoor",
                            Name = "ice cream"
                        },
                        new
                        {
                            Id = new Guid("acda8474-dbb5-44b1-b476-07bd62ee2358"),
                            ActivityLevel = "Medium",
                            Duration = 1.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "park"
                        },
                        new
                        {
                            Id = new Guid("31f7e71f-2e93-45c0-8940-a849fe26b5f8"),
                            ActivityLevel = "Low",
                            Duration = 1.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "christmas lights/lights"
                        },
                        new
                        {
                            Id = new Guid("efa2ddf5-de74-4ca3-b026-612be0f8e688"),
                            ActivityLevel = "High",
                            Duration = 1.5,
                            IndoorOutdoor = "Both",
                            Name = "pickle ball"
                        },
                        new
                        {
                            Id = new Guid("f6167de2-119a-4598-97b0-82ce061295ae"),
                            ActivityLevel = "High",
                            Duration = 1.5,
                            IndoorOutdoor = "Indoor",
                            Name = "raquetball"
                        },
                        new
                        {
                            Id = new Guid("72226db9-1521-4953-9a09-ef4799a30ffd"),
                            ActivityLevel = "Medium",
                            Duration = 2.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "horseback riding"
                        },
                        new
                        {
                            Id = new Guid("22dde74c-1637-4f56-a34c-6a8087a60c45"),
                            ActivityLevel = "High",
                            Duration = 2.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "jetskiing"
                        },
                        new
                        {
                            Id = new Guid("37169b1b-3102-4e30-9d2f-a1a229316dcf"),
                            ActivityLevel = "High",
                            Duration = 3.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "kayaking"
                        },
                        new
                        {
                            Id = new Guid("db19893d-0848-4fe6-99c4-d0d1b9e43226"),
                            ActivityLevel = "Low",
                            Duration = 5.0,
                            IndoorOutdoor = "Both",
                            Name = "road trip"
                        },
                        new
                        {
                            Id = new Guid("3509727f-34f8-46e3-bf78-ea712da01a54"),
                            ActivityLevel = "High",
                            Duration = 4.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "snowboarding"
                        },
                        new
                        {
                            Id = new Guid("ea4e9c67-03e5-4837-a26d-670faf29e511"),
                            ActivityLevel = "High",
                            Duration = 4.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "skiing"
                        },
                        new
                        {
                            Id = new Guid("2303b8ae-f423-41dc-a049-936072092aea"),
                            ActivityLevel = "High",
                            Duration = 3.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "paintballing"
                        },
                        new
                        {
                            Id = new Guid("58e74f56-1870-42e3-9634-d3c1623e6f5a"),
                            ActivityLevel = "High",
                            Duration = 2.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "skydiving"
                        },
                        new
                        {
                            Id = new Guid("5b65fbc4-0854-4754-a842-f73110880e4c"),
                            ActivityLevel = "Low",
                            Duration = 3.0,
                            IndoorOutdoor = "Both",
                            Name = "concert"
                        },
                        new
                        {
                            Id = new Guid("6117c081-1226-4760-a1ed-840fa915175d"),
                            ActivityLevel = "Medium",
                            Duration = 5.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "air show"
                        },
                        new
                        {
                            Id = new Guid("9ac14f97-58f5-4417-ab8b-3cc2d0960557"),
                            ActivityLevel = "Low",
                            Duration = 2.5,
                            IndoorOutdoor = "Indoor",
                            Name = "ballet"
                        },
                        new
                        {
                            Id = new Guid("41389edf-884d-4b77-920a-8fe449601b47"),
                            ActivityLevel = "Low",
                            Duration = 2.5,
                            IndoorOutdoor = "Indoor",
                            Name = "symphony"
                        },
                        new
                        {
                            Id = new Guid("8da154d6-cefb-4533-836e-87e1efb011db"),
                            ActivityLevel = "High",
                            Duration = 3.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "hiking"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
