// <auto-generated />
using System;
using DateFinder.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DateFinder.Storage.Migrations
{
    [DbContext(typeof(DateFinderDbContext))]
    [Migration("20240627200033_changed duration from string to double")]
    partial class changeddurationfromstringtodouble
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DateFinder.Domain.Storage.Date", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivityLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Duration")
                        .HasColumnType("float");

                    b.Property<string>("IndoorOutdoor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rating")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b3e67fe1-46b3-4785-8591-83cde0ccbedb"),
                            ActivityLevel = "High",
                            Duration = 4.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "rock climbing"
                        },
                        new
                        {
                            Id = new Guid("4c087f67-f454-49a9-8855-d2e4f2ba8977"),
                            ActivityLevel = "High",
                            Duration = 2.5,
                            IndoorOutdoor = "Indoor",
                            Name = "indoor rock climbing"
                        },
                        new
                        {
                            Id = new Guid("824ea245-302e-4f93-95e0-110b5fe02de1"),
                            ActivityLevel = "Medium",
                            Duration = 5.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "amusement park"
                        },
                        new
                        {
                            Id = new Guid("4a1b4dcc-3d9d-4b06-a9dd-39daecd3e099"),
                            ActivityLevel = "Medium",
                            Duration = 2.0,
                            IndoorOutdoor = "Indoor",
                            Name = "bowling"
                        },
                        new
                        {
                            Id = new Guid("da7e4d45-c4f3-4143-946e-ef1245dff394"),
                            ActivityLevel = "Medium",
                            Duration = 2.0,
                            IndoorOutdoor = "Both",
                            Name = "mini golf"
                        },
                        new
                        {
                            Id = new Guid("50e4f64a-cbc5-4220-9df6-061f752e5df9"),
                            ActivityLevel = "Medium",
                            Duration = 4.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "golf"
                        },
                        new
                        {
                            Id = new Guid("15a5e705-ec94-49c9-bd73-a3629f23a570"),
                            ActivityLevel = "Medium",
                            Duration = 2.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "driving range"
                        },
                        new
                        {
                            Id = new Guid("570d8b44-1695-4729-ada1-ec3c018e3ee5"),
                            ActivityLevel = "High",
                            Duration = 2.0,
                            IndoorOutdoor = "Indoor",
                            Name = "trampoline park"
                        },
                        new
                        {
                            Id = new Guid("fa55cc14-fdd9-4500-b3f5-9fdfd581ea0a"),
                            ActivityLevel = "Low",
                            Duration = 3.5,
                            IndoorOutdoor = "Both",
                            Name = "live music"
                        },
                        new
                        {
                            Id = new Guid("e3150d6d-8c52-4ea5-be96-a7c3135ee356"),
                            ActivityLevel = "Medium",
                            Duration = 3.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "zoo"
                        },
                        new
                        {
                            Id = new Guid("394b42b8-09af-4f17-a58c-6a38841191cc"),
                            ActivityLevel = "Medium",
                            Duration = 2.5,
                            IndoorOutdoor = "Both",
                            Name = "botanical garden"
                        },
                        new
                        {
                            Id = new Guid("978cbe58-4316-4b8d-9b47-01f4d1544a0f"),
                            ActivityLevel = "Medium",
                            Duration = 3.0,
                            IndoorOutdoor = "Indoor",
                            Name = "museum"
                        },
                        new
                        {
                            Id = new Guid("67f603a9-9b16-4240-9a2b-16aefb62ec1f"),
                            ActivityLevel = "Medium",
                            Duration = 2.5,
                            IndoorOutdoor = "Indoor",
                            Name = "art museum"
                        },
                        new
                        {
                            Id = new Guid("89aa15ce-64cd-4717-9950-1306313bd41d"),
                            ActivityLevel = "Medium",
                            Duration = 2.0,
                            IndoorOutdoor = "Indoor",
                            Name = "mall"
                        },
                        new
                        {
                            Id = new Guid("c963fd9c-1f71-4174-b228-eaf886243854"),
                            ActivityLevel = "Medium",
                            Duration = 1.5,
                            IndoorOutdoor = "Indoor",
                            Name = "laser tag"
                        },
                        new
                        {
                            Id = new Guid("20f8925f-ea37-448c-8b29-072a31e2761d"),
                            ActivityLevel = "High",
                            Duration = 2.5,
                            IndoorOutdoor = "Indoor",
                            Name = "indoor scuba diving"
                        },
                        new
                        {
                            Id = new Guid("b0aa7a04-d9cc-422e-915f-3057149cdc5f"),
                            ActivityLevel = "High",
                            Duration = 1.5,
                            IndoorOutdoor = "Indoor",
                            Name = "indoor skydiving"
                        },
                        new
                        {
                            Id = new Guid("e0f6a286-f238-4121-b21d-3e8adf89a0d1"),
                            ActivityLevel = "Medium",
                            Duration = 2.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "ice castle"
                        },
                        new
                        {
                            Id = new Guid("990d214b-b459-4522-990b-8a4605a74a57"),
                            ActivityLevel = "Low",
                            Duration = 3.0,
                            IndoorOutdoor = "Indoor",
                            Name = "play/musical"
                        },
                        new
                        {
                            Id = new Guid("a06473f9-2d08-4126-8207-50f9a5a05b41"),
                            ActivityLevel = "Medium",
                            Duration = 4.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "beach"
                        },
                        new
                        {
                            Id = new Guid("0ab737d3-e69b-4485-804b-572a01f33a10"),
                            ActivityLevel = "Medium",
                            Duration = 2.0,
                            IndoorOutdoor = "Indoor",
                            Name = "butterfly"
                        },
                        new
                        {
                            Id = new Guid("74293d52-a21b-49f6-be26-72519ea080c1"),
                            ActivityLevel = "Low",
                            Duration = 1.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "farmers market"
                        },
                        new
                        {
                            Id = new Guid("d0a815d3-c28b-48c0-bdc5-4e71f1d1948f"),
                            ActivityLevel = "Low",
                            Duration = 3.5,
                            IndoorOutdoor = "Indoor",
                            Name = "movie"
                        },
                        new
                        {
                            Id = new Guid("b1e261ef-11b7-4650-941a-37415dad42fd"),
                            ActivityLevel = "Low",
                            Duration = 3.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "drive in movie"
                        },
                        new
                        {
                            Id = new Guid("ac031f72-b8bb-4aca-8409-8180578362e6"),
                            ActivityLevel = "Low",
                            Duration = 1.5,
                            IndoorOutdoor = "Indoor",
                            Name = "arcade"
                        },
                        new
                        {
                            Id = new Guid("be428e02-a859-4903-84aa-90f0cac02696"),
                            ActivityLevel = "High",
                            Duration = 1.5,
                            IndoorOutdoor = "Both",
                            Name = "ice skating"
                        },
                        new
                        {
                            Id = new Guid("baf22a0d-d2d2-4108-a917-ced8c709ebed"),
                            ActivityLevel = "High",
                            Duration = 3.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "mountain biking"
                        },
                        new
                        {
                            Id = new Guid("5c829278-21d2-40a4-9ff8-78f63b4ad2b3"),
                            ActivityLevel = "Medium",
                            Duration = 1.5,
                            IndoorOutdoor = "Indoor",
                            Name = "axe throwing"
                        },
                        new
                        {
                            Id = new Guid("50a022ec-79f9-4fd9-9ba3-22e02b9313e6"),
                            ActivityLevel = "Medium",
                            Duration = 1.5,
                            IndoorOutdoor = "Both",
                            Name = "archery"
                        },
                        new
                        {
                            Id = new Guid("0594cbb2-a3cb-4941-9540-e2ddcb1ab4c6"),
                            ActivityLevel = "Low",
                            Duration = 1.0,
                            IndoorOutdoor = "Indoor",
                            Name = "boba"
                        },
                        new
                        {
                            Id = new Guid("2c7e2f7f-112c-49b8-b569-ebd9f4e9fc7c"),
                            ActivityLevel = "Low",
                            Duration = 1.0,
                            IndoorOutdoor = "Indoor",
                            Name = "ice cream"
                        },
                        new
                        {
                            Id = new Guid("875a446c-c9f0-47bc-b8de-5cf7ae9ce9e0"),
                            ActivityLevel = "Medium",
                            Duration = 1.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "park"
                        },
                        new
                        {
                            Id = new Guid("be02f7ff-3dd4-4918-89f1-cd2fca506680"),
                            ActivityLevel = "Low",
                            Duration = 1.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "christmas lights/lights"
                        },
                        new
                        {
                            Id = new Guid("b527564a-9c0b-4800-bc7c-d43b27c1f1ad"),
                            ActivityLevel = "High",
                            Duration = 1.5,
                            IndoorOutdoor = "Both",
                            Name = "pickle ball"
                        },
                        new
                        {
                            Id = new Guid("020be98a-c321-4c58-96a5-78db7d9917d0"),
                            ActivityLevel = "High",
                            Duration = 1.5,
                            IndoorOutdoor = "Indoor",
                            Name = "raquetball"
                        },
                        new
                        {
                            Id = new Guid("ed24f2d9-8c34-4a1a-97cc-befe3824509a"),
                            ActivityLevel = "Medium",
                            Duration = 2.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "horseback riding"
                        },
                        new
                        {
                            Id = new Guid("4b2423b4-9ca1-41c7-9232-82f5e6f236c9"),
                            ActivityLevel = "High",
                            Duration = 2.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "jetskiing"
                        },
                        new
                        {
                            Id = new Guid("acebc146-c641-439d-83c6-189417efa849"),
                            ActivityLevel = "High",
                            Duration = 3.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "kayaking"
                        },
                        new
                        {
                            Id = new Guid("d67498b4-39f4-4773-941e-3873bd744398"),
                            ActivityLevel = "Low",
                            Duration = 5.0,
                            IndoorOutdoor = "Both",
                            Name = "road trip"
                        },
                        new
                        {
                            Id = new Guid("ebd3bbcf-593a-4766-8227-e44dee008377"),
                            ActivityLevel = "High",
                            Duration = 4.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "snowboarding"
                        },
                        new
                        {
                            Id = new Guid("b35354c6-82fe-47cb-b399-302022b0a782"),
                            ActivityLevel = "High",
                            Duration = 4.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "skiing"
                        },
                        new
                        {
                            Id = new Guid("c317e38a-2691-4f37-a413-7826d0ecc894"),
                            ActivityLevel = "High",
                            Duration = 3.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "paintballing"
                        },
                        new
                        {
                            Id = new Guid("18d84169-4902-48e6-b6a6-2329581c1c8e"),
                            ActivityLevel = "High",
                            Duration = 2.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "skydiving"
                        },
                        new
                        {
                            Id = new Guid("89848da3-65ad-4b74-9394-16f71adc82a1"),
                            ActivityLevel = "Low",
                            Duration = 3.0,
                            IndoorOutdoor = "Both",
                            Name = "concert"
                        },
                        new
                        {
                            Id = new Guid("3e89c162-200b-432c-9b2a-4bded07f0107"),
                            ActivityLevel = "Medium",
                            Duration = 5.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "air show"
                        },
                        new
                        {
                            Id = new Guid("c8d2f3ba-5a93-4426-8938-00febc1e6280"),
                            ActivityLevel = "Low",
                            Duration = 2.5,
                            IndoorOutdoor = "Indoor",
                            Name = "ballet"
                        },
                        new
                        {
                            Id = new Guid("e284bed2-62e2-473f-8a36-eacc58b488f2"),
                            ActivityLevel = "Low",
                            Duration = 2.5,
                            IndoorOutdoor = "Indoor",
                            Name = "symphony"
                        },
                        new
                        {
                            Id = new Guid("629ff2c4-63ce-4502-ae29-893b7b155f14"),
                            ActivityLevel = "High",
                            Duration = 3.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "hiking"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
