// <auto-generated />
using System;
using DateFinder.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DateFinder.Storage.Migrations
{
    [DbContext(typeof(DateFinderDbContext))]
    [Migration("20240716002121_deleted some entries from database")]
    partial class deletedsomeentriesfromdatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DateFinder.Domain.Storage.Date", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivityLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Duration")
                        .HasColumnType("float");

                    b.Property<string>("IndoorOutdoor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rating")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c56085b3-07bf-45c9-983c-14c665c70c8e"),
                            ActivityLevel = "High",
                            Duration = 4.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "rock climbing"
                        },
                        new
                        {
                            Id = new Guid("0de41b5b-23f7-4ff2-bec4-36d0be2f4254"),
                            ActivityLevel = "High",
                            Duration = 2.5,
                            IndoorOutdoor = "Indoor",
                            Name = "indoor rock climbing"
                        },
                        new
                        {
                            Id = new Guid("e700c095-9c68-40ca-aab5-f6bddf67cc27"),
                            ActivityLevel = "Medium",
                            Duration = 5.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "amusement park"
                        },
                        new
                        {
                            Id = new Guid("8c2f6944-1254-4e1c-a5f2-944a5699e8ed"),
                            ActivityLevel = "Medium",
                            Duration = 2.0,
                            IndoorOutdoor = "Indoor",
                            Name = "bowling"
                        },
                        new
                        {
                            Id = new Guid("794b0952-58a3-429d-97ac-1a932c61a708"),
                            ActivityLevel = "Medium",
                            Duration = 2.0,
                            IndoorOutdoor = "Both",
                            Name = "mini golf"
                        },
                        new
                        {
                            Id = new Guid("332d5194-e2d7-47ab-ad2a-6f4f86d229ed"),
                            ActivityLevel = "Medium",
                            Duration = 4.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "golf"
                        },
                        new
                        {
                            Id = new Guid("ebefa09e-e438-48cc-a58b-bd4232339540"),
                            ActivityLevel = "Medium",
                            Duration = 2.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "driving range"
                        },
                        new
                        {
                            Id = new Guid("b277a378-424d-4add-8481-9d2f9061781a"),
                            ActivityLevel = "High",
                            Duration = 2.0,
                            IndoorOutdoor = "Indoor",
                            Name = "trampoline park"
                        },
                        new
                        {
                            Id = new Guid("4c12d731-6b4e-4a2c-8133-a0d5c36311aa"),
                            ActivityLevel = "Low",
                            Duration = 3.5,
                            IndoorOutdoor = "Both",
                            Name = "live music"
                        },
                        new
                        {
                            Id = new Guid("1d67a826-7282-4a85-90bd-9b4201660a6d"),
                            ActivityLevel = "Medium",
                            Duration = 3.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "zoo"
                        },
                        new
                        {
                            Id = new Guid("3858c4c3-f5b7-47d6-b18e-2e62435b45c9"),
                            ActivityLevel = "Medium",
                            Duration = 2.5,
                            IndoorOutdoor = "Both",
                            Name = "botanical garden"
                        },
                        new
                        {
                            Id = new Guid("89c94ed8-2064-4fca-b3a0-ad2e5dd8a089"),
                            ActivityLevel = "Medium",
                            Duration = 3.0,
                            IndoorOutdoor = "Indoor",
                            Name = "museum"
                        },
                        new
                        {
                            Id = new Guid("67e8e03e-06c9-46d0-85d8-a02284a445c4"),
                            ActivityLevel = "Medium",
                            Duration = 2.5,
                            IndoorOutdoor = "Indoor",
                            Name = "art museum"
                        },
                        new
                        {
                            Id = new Guid("78bda27d-2da0-407f-9c45-a5d3400afccc"),
                            ActivityLevel = "Medium",
                            Duration = 2.0,
                            IndoorOutdoor = "Indoor",
                            Name = "mall"
                        },
                        new
                        {
                            Id = new Guid("3f8333f0-22ce-4875-8206-d47c20ea50f6"),
                            ActivityLevel = "Medium",
                            Duration = 1.5,
                            IndoorOutdoor = "Indoor",
                            Name = "laser tag"
                        },
                        new
                        {
                            Id = new Guid("6f975300-4319-45c0-af07-53212fbda88d"),
                            ActivityLevel = "High",
                            Duration = 2.5,
                            IndoorOutdoor = "Indoor",
                            Name = "indoor scuba diving"
                        },
                        new
                        {
                            Id = new Guid("dc21cd2c-bfeb-4293-b231-574f29cdb727"),
                            ActivityLevel = "High",
                            Duration = 1.5,
                            IndoorOutdoor = "Indoor",
                            Name = "indoor skydiving"
                        },
                        new
                        {
                            Id = new Guid("e6167230-7b15-4a12-886f-54f4358c5334"),
                            ActivityLevel = "Medium",
                            Duration = 2.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "ice castle"
                        },
                        new
                        {
                            Id = new Guid("19203e56-548c-42a9-9dc4-33bc1374048c"),
                            ActivityLevel = "Low",
                            Duration = 3.0,
                            IndoorOutdoor = "Indoor",
                            Name = "play/musical"
                        },
                        new
                        {
                            Id = new Guid("be0b8369-2d04-4873-9627-34fbbf4f5f4f"),
                            ActivityLevel = "Medium",
                            Duration = 4.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "beach"
                        },
                        new
                        {
                            Id = new Guid("40370dc2-96ea-4f14-a589-877ad811dd26"),
                            ActivityLevel = "Medium",
                            Duration = 2.0,
                            IndoorOutdoor = "Indoor",
                            Name = "butterfly"
                        },
                        new
                        {
                            Id = new Guid("d0bf7427-1112-4270-b782-d092573172a0"),
                            ActivityLevel = "Low",
                            Duration = 1.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "farmers market"
                        },
                        new
                        {
                            Id = new Guid("ed5bbfb0-32ff-4762-9728-a72969fae2b2"),
                            ActivityLevel = "Low",
                            Duration = 3.5,
                            IndoorOutdoor = "Indoor",
                            Name = "movie"
                        },
                        new
                        {
                            Id = new Guid("801460d4-3926-4e98-ab1a-cdcedf9d2233"),
                            ActivityLevel = "Low",
                            Duration = 3.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "drive in movie"
                        },
                        new
                        {
                            Id = new Guid("a13e72d8-7ab2-4269-bea7-f4987fb5485a"),
                            ActivityLevel = "Low",
                            Duration = 1.5,
                            IndoorOutdoor = "Indoor",
                            Name = "arcade"
                        },
                        new
                        {
                            Id = new Guid("6532fd4b-2c0f-463a-9973-78450f800042"),
                            ActivityLevel = "High",
                            Duration = 1.5,
                            IndoorOutdoor = "Both",
                            Name = "ice skating"
                        },
                        new
                        {
                            Id = new Guid("ec8545c8-648a-4da0-9550-59bf7088851d"),
                            ActivityLevel = "High",
                            Duration = 3.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "mountain biking"
                        },
                        new
                        {
                            Id = new Guid("55fff685-fc6e-4ebd-9936-2c6875b64f6e"),
                            ActivityLevel = "Medium",
                            Duration = 1.5,
                            IndoorOutdoor = "Indoor",
                            Name = "axe throwing"
                        },
                        new
                        {
                            Id = new Guid("01e9e7cd-6b28-4edc-b5f3-850ec8ec8dd3"),
                            ActivityLevel = "Medium",
                            Duration = 1.5,
                            IndoorOutdoor = "Both",
                            Name = "archery"
                        },
                        new
                        {
                            Id = new Guid("d43c14ac-6b1c-4a64-9571-6e1a077dd54d"),
                            ActivityLevel = "Low",
                            Duration = 1.0,
                            IndoorOutdoor = "Indoor",
                            Name = "boba"
                        },
                        new
                        {
                            Id = new Guid("f5a609d7-4f0c-472e-926a-d05b047020b9"),
                            ActivityLevel = "Low",
                            Duration = 1.0,
                            IndoorOutdoor = "Indoor",
                            Name = "ice cream"
                        },
                        new
                        {
                            Id = new Guid("64053731-0d85-43bd-82d4-5b0fd6955831"),
                            ActivityLevel = "Medium",
                            Duration = 1.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "park"
                        },
                        new
                        {
                            Id = new Guid("8891b4ac-a15c-47d4-be94-7c43c2ff7fd9"),
                            ActivityLevel = "Low",
                            Duration = 1.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "christmas lights"
                        },
                        new
                        {
                            Id = new Guid("a64b9a42-6cdd-4531-9542-1a9319b56066"),
                            ActivityLevel = "High",
                            Duration = 1.5,
                            IndoorOutdoor = "Both",
                            Name = "pickle ball"
                        },
                        new
                        {
                            Id = new Guid("697fe27d-7f9c-4ae1-93bc-d204026d4385"),
                            ActivityLevel = "High",
                            Duration = 1.5,
                            IndoorOutdoor = "Indoor",
                            Name = "raquetball"
                        },
                        new
                        {
                            Id = new Guid("4d234db2-f188-4c23-9f94-f29c91747806"),
                            ActivityLevel = "Medium",
                            Duration = 2.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "horseback riding"
                        },
                        new
                        {
                            Id = new Guid("6f56b52f-dcd8-4148-b1f0-b1770d9d6f98"),
                            ActivityLevel = "High",
                            Duration = 2.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "jetskiing"
                        },
                        new
                        {
                            Id = new Guid("e18f93f0-e190-44dc-9fda-700e225d19cc"),
                            ActivityLevel = "High",
                            Duration = 3.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "kayaking"
                        },
                        new
                        {
                            Id = new Guid("68aa7622-d0fe-4e57-a8c4-d625b7190fca"),
                            ActivityLevel = "Low",
                            Duration = 5.0,
                            IndoorOutdoor = "Both",
                            Name = "road trip"
                        },
                        new
                        {
                            Id = new Guid("2c474e15-d3e4-4146-8efb-50948e0eab32"),
                            ActivityLevel = "High",
                            Duration = 4.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "skiing"
                        },
                        new
                        {
                            Id = new Guid("4d7cf3a2-cc57-4fec-8226-d5b17a5c5937"),
                            ActivityLevel = "High",
                            Duration = 3.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "paintballing"
                        },
                        new
                        {
                            Id = new Guid("201a8429-e356-4839-bc84-d2b030c8bc67"),
                            ActivityLevel = "High",
                            Duration = 2.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "skydiving"
                        },
                        new
                        {
                            Id = new Guid("549cfed1-853a-42cb-ab58-39df89d329ae"),
                            ActivityLevel = "Low",
                            Duration = 3.0,
                            IndoorOutdoor = "Both",
                            Name = "concert"
                        },
                        new
                        {
                            Id = new Guid("6aaf8d45-66d7-4340-96bd-fa57e6ff31c4"),
                            ActivityLevel = "Medium",
                            Duration = 5.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "air show"
                        },
                        new
                        {
                            Id = new Guid("a962c555-9e71-4f8b-8f6e-374c419ff0d1"),
                            ActivityLevel = "Low",
                            Duration = 2.5,
                            IndoorOutdoor = "Indoor",
                            Name = "symphony"
                        },
                        new
                        {
                            Id = new Guid("f04e418e-241a-4359-8ad1-ebd3289bb240"),
                            ActivityLevel = "High",
                            Duration = 3.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "hiking"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
