// <auto-generated />
using System;
using DateFinder.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DateFinder.Storage.Migrations
{
    [DbContext(typeof(DateFinderDbContext))]
    [Migration("20240627231941_reseeding database")]
    partial class reseedingdatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DateFinder.Domain.Storage.Date", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivityLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Duration")
                        .HasColumnType("float");

                    b.Property<string>("IndoorOutdoor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rating")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("49aa8435-b305-42fb-b4e4-1fac1b21ce49"),
                            ActivityLevel = "High",
                            Duration = 4.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "rock climbing"
                        },
                        new
                        {
                            Id = new Guid("0e0a8c58-9080-474f-ad5e-2456a68ba451"),
                            ActivityLevel = "High",
                            Duration = 2.5,
                            IndoorOutdoor = "Indoor",
                            Name = "indoor rock climbing"
                        },
                        new
                        {
                            Id = new Guid("febc60ec-32e5-4da9-a241-3d4cf24f35ea"),
                            ActivityLevel = "Medium",
                            Duration = 5.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "amusement park"
                        },
                        new
                        {
                            Id = new Guid("13f03c1f-f4ab-48c3-9a4f-3e6ed8aff629"),
                            ActivityLevel = "Medium",
                            Duration = 2.0,
                            IndoorOutdoor = "Indoor",
                            Name = "bowling"
                        },
                        new
                        {
                            Id = new Guid("09375188-bc7e-46f6-b79c-69973ed965ce"),
                            ActivityLevel = "Medium",
                            Duration = 2.0,
                            IndoorOutdoor = "Both",
                            Name = "mini golf"
                        },
                        new
                        {
                            Id = new Guid("6662013e-4ad8-48da-a7a7-3ce2919e88d8"),
                            ActivityLevel = "Medium",
                            Duration = 4.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "golf"
                        },
                        new
                        {
                            Id = new Guid("47f4a54c-57e6-40cc-951e-ab60cd6a371d"),
                            ActivityLevel = "Medium",
                            Duration = 2.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "driving range"
                        },
                        new
                        {
                            Id = new Guid("6d8cc3dd-0a72-4848-89eb-9445927a3b9d"),
                            ActivityLevel = "High",
                            Duration = 2.0,
                            IndoorOutdoor = "Indoor",
                            Name = "trampoline park"
                        },
                        new
                        {
                            Id = new Guid("a12e5f6a-48d8-4ba8-9c61-dfe6f304fee6"),
                            ActivityLevel = "Low",
                            Duration = 3.5,
                            IndoorOutdoor = "Both",
                            Name = "live music"
                        },
                        new
                        {
                            Id = new Guid("0ee32973-8e62-4d78-8f92-08c1c8812808"),
                            ActivityLevel = "Medium",
                            Duration = 3.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "zoo"
                        },
                        new
                        {
                            Id = new Guid("70559920-5d4f-4a73-b24c-8b39ad662ecd"),
                            ActivityLevel = "Medium",
                            Duration = 2.5,
                            IndoorOutdoor = "Both",
                            Name = "botanical garden"
                        },
                        new
                        {
                            Id = new Guid("a83606f9-a23b-4b47-bed0-d92676ab42df"),
                            ActivityLevel = "Medium",
                            Duration = 3.0,
                            IndoorOutdoor = "Indoor",
                            Name = "museum"
                        },
                        new
                        {
                            Id = new Guid("6326fb39-983d-4ad1-b612-5b81ffe29ff7"),
                            ActivityLevel = "Medium",
                            Duration = 2.5,
                            IndoorOutdoor = "Indoor",
                            Name = "art museum"
                        },
                        new
                        {
                            Id = new Guid("6193ab6c-6d28-4581-bc2d-20fb9cf9bba5"),
                            ActivityLevel = "Medium",
                            Duration = 2.0,
                            IndoorOutdoor = "Indoor",
                            Name = "mall"
                        },
                        new
                        {
                            Id = new Guid("a0c64e67-1885-4ee7-b658-29f389af8ae0"),
                            ActivityLevel = "Medium",
                            Duration = 1.5,
                            IndoorOutdoor = "Indoor",
                            Name = "laser tag"
                        },
                        new
                        {
                            Id = new Guid("2f82285e-78a6-44d2-b364-9bbb85489731"),
                            ActivityLevel = "High",
                            Duration = 2.5,
                            IndoorOutdoor = "Indoor",
                            Name = "indoor scuba diving"
                        },
                        new
                        {
                            Id = new Guid("d5e1d6e7-eeb6-4ed2-a233-16a18f7381a3"),
                            ActivityLevel = "High",
                            Duration = 1.5,
                            IndoorOutdoor = "Indoor",
                            Name = "indoor skydiving"
                        },
                        new
                        {
                            Id = new Guid("865da27f-a05a-4dfe-bbc2-02c7adb0f111"),
                            ActivityLevel = "Medium",
                            Duration = 2.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "ice castle"
                        },
                        new
                        {
                            Id = new Guid("01b6e4c6-721c-4bd9-8078-491ad1499015"),
                            ActivityLevel = "Low",
                            Duration = 3.0,
                            IndoorOutdoor = "Indoor",
                            Name = "play/musical"
                        },
                        new
                        {
                            Id = new Guid("61575de3-85bf-425e-ba8d-d0a90daf785b"),
                            ActivityLevel = "Medium",
                            Duration = 4.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "beach"
                        },
                        new
                        {
                            Id = new Guid("8b36a925-1c29-44ad-b6db-ccacd4ed98b9"),
                            ActivityLevel = "Medium",
                            Duration = 2.0,
                            IndoorOutdoor = "Indoor",
                            Name = "butterfly"
                        },
                        new
                        {
                            Id = new Guid("a246ed1a-1b53-4c1b-b7ff-aa4cfd876bae"),
                            ActivityLevel = "Low",
                            Duration = 1.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "farmers market"
                        },
                        new
                        {
                            Id = new Guid("a329dde3-58dc-4c09-9c3b-75547f6a62c1"),
                            ActivityLevel = "Low",
                            Duration = 3.5,
                            IndoorOutdoor = "Indoor",
                            Name = "movie"
                        },
                        new
                        {
                            Id = new Guid("120fe3fb-7d35-4443-b2a7-c18a335bfb93"),
                            ActivityLevel = "Low",
                            Duration = 3.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "drive in movie"
                        },
                        new
                        {
                            Id = new Guid("528f28a6-eedc-4e79-b13f-23f4278b82b2"),
                            ActivityLevel = "Low",
                            Duration = 1.5,
                            IndoorOutdoor = "Indoor",
                            Name = "arcade"
                        },
                        new
                        {
                            Id = new Guid("5741d76d-c752-4382-b790-c5685dcc3bef"),
                            ActivityLevel = "High",
                            Duration = 1.5,
                            IndoorOutdoor = "Both",
                            Name = "ice skating"
                        },
                        new
                        {
                            Id = new Guid("cd6ecef7-7764-44c1-9a52-c222423fdf7f"),
                            ActivityLevel = "High",
                            Duration = 3.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "mountain biking"
                        },
                        new
                        {
                            Id = new Guid("0731f1f8-33f2-4cbb-bd27-689b4bb0dfdd"),
                            ActivityLevel = "Medium",
                            Duration = 1.5,
                            IndoorOutdoor = "Indoor",
                            Name = "axe throwing"
                        },
                        new
                        {
                            Id = new Guid("748db71d-a136-42f8-9417-4970374dbd78"),
                            ActivityLevel = "Medium",
                            Duration = 1.5,
                            IndoorOutdoor = "Both",
                            Name = "archery"
                        },
                        new
                        {
                            Id = new Guid("0d7f1045-ea6f-4e2d-af80-6eb72b020efa"),
                            ActivityLevel = "Low",
                            Duration = 1.0,
                            IndoorOutdoor = "Indoor",
                            Name = "boba"
                        },
                        new
                        {
                            Id = new Guid("289dc090-3a99-4bee-b75b-b7eec822d656"),
                            ActivityLevel = "Low",
                            Duration = 1.0,
                            IndoorOutdoor = "Indoor",
                            Name = "ice cream"
                        },
                        new
                        {
                            Id = new Guid("0a1bb980-2605-4aaa-aa6c-f7d0f7c8799a"),
                            ActivityLevel = "Medium",
                            Duration = 1.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "park"
                        },
                        new
                        {
                            Id = new Guid("44c075fb-9d44-450d-98e2-c7be6ff0f6d9"),
                            ActivityLevel = "Low",
                            Duration = 1.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "christmas lights/lights"
                        },
                        new
                        {
                            Id = new Guid("44dec13d-95b5-42f9-97c4-f15d06a997f1"),
                            ActivityLevel = "High",
                            Duration = 1.5,
                            IndoorOutdoor = "Both",
                            Name = "pickle ball"
                        },
                        new
                        {
                            Id = new Guid("a96e99d9-60eb-4f11-927a-7c578c95212d"),
                            ActivityLevel = "High",
                            Duration = 1.5,
                            IndoorOutdoor = "Indoor",
                            Name = "raquetball"
                        },
                        new
                        {
                            Id = new Guid("fd12f861-87b4-4700-8a8d-051bbf7c409c"),
                            ActivityLevel = "Medium",
                            Duration = 2.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "horseback riding"
                        },
                        new
                        {
                            Id = new Guid("8df752e8-d994-466b-81e5-13762e950567"),
                            ActivityLevel = "High",
                            Duration = 2.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "jetskiing"
                        },
                        new
                        {
                            Id = new Guid("1b84cba9-8cc3-4e00-8d8b-2307043bffb6"),
                            ActivityLevel = "High",
                            Duration = 3.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "kayaking"
                        },
                        new
                        {
                            Id = new Guid("c5f20399-f37d-482b-9f9f-351a71c2fab5"),
                            ActivityLevel = "Low",
                            Duration = 5.0,
                            IndoorOutdoor = "Both",
                            Name = "road trip"
                        },
                        new
                        {
                            Id = new Guid("15de9d4a-a980-40de-abde-cd4409267e99"),
                            ActivityLevel = "High",
                            Duration = 4.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "snowboarding"
                        },
                        new
                        {
                            Id = new Guid("a9479af8-1195-4078-b533-4920387a4cc4"),
                            ActivityLevel = "High",
                            Duration = 4.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "skiing"
                        },
                        new
                        {
                            Id = new Guid("13319364-6b92-4756-980f-8f1ff4a915fd"),
                            ActivityLevel = "High",
                            Duration = 3.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "paintballing"
                        },
                        new
                        {
                            Id = new Guid("167d453c-b15d-42b0-85a2-78e74277041c"),
                            ActivityLevel = "High",
                            Duration = 2.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "skydiving"
                        },
                        new
                        {
                            Id = new Guid("74e7a7a2-267f-43ff-8666-8337313aaea1"),
                            ActivityLevel = "Low",
                            Duration = 3.0,
                            IndoorOutdoor = "Both",
                            Name = "concert"
                        },
                        new
                        {
                            Id = new Guid("8010126d-3885-454f-ad5c-00a4ad400ec3"),
                            ActivityLevel = "Medium",
                            Duration = 5.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "air show"
                        },
                        new
                        {
                            Id = new Guid("8a865142-da0d-4e3f-b46e-f84e6378c976"),
                            ActivityLevel = "Low",
                            Duration = 2.5,
                            IndoorOutdoor = "Indoor",
                            Name = "ballet"
                        },
                        new
                        {
                            Id = new Guid("5799c3f7-c0cc-4849-9b38-51144b999b3e"),
                            ActivityLevel = "Low",
                            Duration = 2.5,
                            IndoorOutdoor = "Indoor",
                            Name = "symphony"
                        },
                        new
                        {
                            Id = new Guid("5c0d93c7-25a1-4730-9544-1f4294a14f93"),
                            ActivityLevel = "High",
                            Duration = 3.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "hiking"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
