// <auto-generated />
using System;
using DateFinder.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DateFinder.Storage.Migrations
{
    [DbContext(typeof(DateFinderDbContext))]
    partial class DateFinderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DateFinder.Models.Date", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndoorOutdoor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MyProperty")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rating")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Date");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ac22767e-2b38-4c93-b5c8-d17a6e8ee6e1"),
                            ActivityLevel = "High",
                            Duration = "4",
                            IndoorOutdoor = "Outdoor",
                            MyProperty = 0,
                            Name = "rock climbing"
                        },
                        new
                        {
                            Id = new Guid("12845b63-fa0e-4b23-813a-3d380ec3e485"),
                            ActivityLevel = "High",
                            Duration = "2.5",
                            IndoorOutdoor = "Indoor",
                            MyProperty = 0,
                            Name = "indoor rock climbing"
                        },
                        new
                        {
                            Id = new Guid("d0d7e7e2-391d-4567-9ffd-e7f89a414b02"),
                            ActivityLevel = "Medium",
                            Duration = "5",
                            IndoorOutdoor = "Outdoor",
                            MyProperty = 0,
                            Name = "amusement park"
                        },
                        new
                        {
                            Id = new Guid("f4e2ab78-5ecf-4b93-8b49-c646829ea885"),
                            ActivityLevel = "Medium",
                            Duration = "2",
                            IndoorOutdoor = "Indoor",
                            MyProperty = 0,
                            Name = "bowling"
                        },
                        new
                        {
                            Id = new Guid("87e12bda-c19d-46c1-8760-65723db72070"),
                            ActivityLevel = "Medium",
                            Duration = "2",
                            IndoorOutdoor = "Both",
                            MyProperty = 0,
                            Name = "mini golf"
                        },
                        new
                        {
                            Id = new Guid("b70d8c3f-d17e-45e3-8d2a-f24580730f5c"),
                            ActivityLevel = "Medium",
                            Duration = "4",
                            IndoorOutdoor = "Outdoor",
                            MyProperty = 0,
                            Name = "golf"
                        },
                        new
                        {
                            Id = new Guid("9a010a9f-937e-4b3d-9f49-7978d84b329b"),
                            ActivityLevel = "Medium",
                            Duration = "2",
                            IndoorOutdoor = "Outdoor",
                            MyProperty = 0,
                            Name = "driving range"
                        },
                        new
                        {
                            Id = new Guid("2cd94e1c-40c2-4577-990d-67749ef1a92f"),
                            ActivityLevel = "High",
                            Duration = "2",
                            IndoorOutdoor = "Indoor",
                            MyProperty = 0,
                            Name = "trampoline park"
                        },
                        new
                        {
                            Id = new Guid("67030e81-fbe2-4000-8a5b-fa559f740e58"),
                            ActivityLevel = "Low",
                            Duration = "3.5",
                            IndoorOutdoor = "Both",
                            MyProperty = 0,
                            Name = "live music"
                        },
                        new
                        {
                            Id = new Guid("dfac533c-e79f-45fd-8dce-6d7157d6bded"),
                            ActivityLevel = "Medium",
                            Duration = "3.5",
                            IndoorOutdoor = "Outdoor",
                            MyProperty = 0,
                            Name = "zoo"
                        },
                        new
                        {
                            Id = new Guid("38f5bedd-6fcd-4104-9612-24fac6e65ae1"),
                            ActivityLevel = "Medium",
                            Duration = "2.5",
                            IndoorOutdoor = "Both",
                            MyProperty = 0,
                            Name = "botanical garden"
                        },
                        new
                        {
                            Id = new Guid("99b8d6af-1c34-4985-a0d8-d6d42ab21dc2"),
                            ActivityLevel = "Medium",
                            Duration = "3",
                            IndoorOutdoor = "Indoor",
                            MyProperty = 0,
                            Name = "museum"
                        },
                        new
                        {
                            Id = new Guid("a34ebccc-80c9-48f9-8fae-397f5d3eeb19"),
                            ActivityLevel = "Medium",
                            Duration = "2.5",
                            IndoorOutdoor = "Indoor",
                            MyProperty = 0,
                            Name = "art museum"
                        },
                        new
                        {
                            Id = new Guid("105c536f-8a19-4a6e-8cfa-58923bd90f5a"),
                            ActivityLevel = "Medium",
                            Duration = "2",
                            IndoorOutdoor = "Indoor",
                            MyProperty = 0,
                            Name = "mall"
                        },
                        new
                        {
                            Id = new Guid("f70870b1-5ef2-4cc0-bc7a-7926a8bfc8b4"),
                            ActivityLevel = "Medium",
                            Duration = "1.5",
                            IndoorOutdoor = "Indoor",
                            MyProperty = 0,
                            Name = "laser tag"
                        },
                        new
                        {
                            Id = new Guid("bbbdd4c2-ae88-4077-a229-5d71f2003338"),
                            ActivityLevel = "High",
                            Duration = "2.5",
                            IndoorOutdoor = "Indoor",
                            MyProperty = 0,
                            Name = "indoor scuba diving"
                        },
                        new
                        {
                            Id = new Guid("36502af6-1d1f-462d-b82d-3c9f613291b2"),
                            ActivityLevel = "High",
                            Duration = "1.5",
                            IndoorOutdoor = "Indoor",
                            MyProperty = 0,
                            Name = "indoor skydiving"
                        },
                        new
                        {
                            Id = new Guid("9155e81f-cffa-4163-a88f-1e946eef1893"),
                            ActivityLevel = "Medium",
                            Duration = "2",
                            IndoorOutdoor = "Outdoor",
                            MyProperty = 0,
                            Name = "ice castle"
                        },
                        new
                        {
                            Id = new Guid("b75be1ed-d65f-4e79-8cfc-08db4dbab62c"),
                            ActivityLevel = "Low",
                            Duration = "3",
                            IndoorOutdoor = "Indoor",
                            MyProperty = 0,
                            Name = "play/musical"
                        },
                        new
                        {
                            Id = new Guid("8ccbd251-da62-4477-a498-f191c7efc900"),
                            ActivityLevel = "Medium",
                            Duration = "4",
                            IndoorOutdoor = "Outdoor",
                            MyProperty = 0,
                            Name = "beach"
                        },
                        new
                        {
                            Id = new Guid("f9d3d807-0707-4594-af18-dccf376d498e"),
                            ActivityLevel = "Medium",
                            Duration = "2",
                            IndoorOutdoor = "Indoor",
                            MyProperty = 0,
                            Name = "butterfly"
                        },
                        new
                        {
                            Id = new Guid("e812751d-a952-40f2-bb0e-17216080e236"),
                            ActivityLevel = "Low",
                            Duration = "1.5",
                            IndoorOutdoor = "Outdoor",
                            MyProperty = 0,
                            Name = "farmers market"
                        },
                        new
                        {
                            Id = new Guid("436f7fac-2ba4-4448-84d0-ee60170860bb"),
                            ActivityLevel = "Low",
                            Duration = "3.5",
                            IndoorOutdoor = "Indoor",
                            MyProperty = 0,
                            Name = "movie"
                        },
                        new
                        {
                            Id = new Guid("c85d6c33-4782-4ad8-99be-bace4a80fee3"),
                            ActivityLevel = "Low",
                            Duration = "3.5",
                            IndoorOutdoor = "Outdoor",
                            MyProperty = 0,
                            Name = "drive in movie"
                        },
                        new
                        {
                            Id = new Guid("7688da2f-353b-407b-81c1-d68c563e1ded"),
                            ActivityLevel = "Low",
                            Duration = "1.5",
                            IndoorOutdoor = "Indoor",
                            MyProperty = 0,
                            Name = "arcade"
                        },
                        new
                        {
                            Id = new Guid("5de5544e-7493-4f5f-808c-d40026d220d7"),
                            ActivityLevel = "High",
                            Duration = "1.5",
                            IndoorOutdoor = "Both",
                            MyProperty = 0,
                            Name = "ice skating"
                        },
                        new
                        {
                            Id = new Guid("f4007407-6a14-42d5-913b-25ba088ba232"),
                            ActivityLevel = "High",
                            Duration = "3",
                            IndoorOutdoor = "Outdoor",
                            MyProperty = 0,
                            Name = "mountain biking"
                        },
                        new
                        {
                            Id = new Guid("dff9b5b5-9bc3-4fc4-b36c-d43c4b03417f"),
                            ActivityLevel = "Medium",
                            Duration = "1.5",
                            IndoorOutdoor = "Indoor",
                            MyProperty = 0,
                            Name = "axe throwing"
                        },
                        new
                        {
                            Id = new Guid("c551e3c7-cd8a-475d-8951-4b6edaac6ec3"),
                            ActivityLevel = "Medium",
                            Duration = "1.5",
                            IndoorOutdoor = "Both",
                            MyProperty = 0,
                            Name = "archery"
                        },
                        new
                        {
                            Id = new Guid("be6e1ff8-aaf6-4b39-8d6c-0610d4182594"),
                            ActivityLevel = "Low",
                            Duration = "1",
                            IndoorOutdoor = "Indoor",
                            MyProperty = 0,
                            Name = "boba"
                        },
                        new
                        {
                            Id = new Guid("5dd4f244-6b34-4c34-8858-4b14e223a6f3"),
                            ActivityLevel = "Low",
                            Duration = "1",
                            IndoorOutdoor = "Indoor",
                            MyProperty = 0,
                            Name = "ice cream"
                        },
                        new
                        {
                            Id = new Guid("5c8cd1a7-b032-434a-844b-6bb6f42b557b"),
                            ActivityLevel = "Medium",
                            Duration = "1.5",
                            IndoorOutdoor = "Outdoor",
                            MyProperty = 0,
                            Name = "park"
                        },
                        new
                        {
                            Id = new Guid("70d797b3-0362-4372-b082-c59de71ef49d"),
                            ActivityLevel = "Low",
                            Duration = "1.5",
                            IndoorOutdoor = "Outdoor",
                            MyProperty = 0,
                            Name = "christmas lights/lights"
                        },
                        new
                        {
                            Id = new Guid("d744d5db-235d-4978-b2c8-5233bc36ab52"),
                            ActivityLevel = "High",
                            Duration = "1.5",
                            IndoorOutdoor = "Both",
                            MyProperty = 0,
                            Name = "pickle ball"
                        },
                        new
                        {
                            Id = new Guid("e7f5c0e6-8960-4fd9-8ac7-b51cb370b487"),
                            ActivityLevel = "High",
                            Duration = "1.5",
                            IndoorOutdoor = "Indoor",
                            MyProperty = 0,
                            Name = "raquetball"
                        },
                        new
                        {
                            Id = new Guid("a7017a4d-b86d-4350-98ad-058551bf1045"),
                            ActivityLevel = "Medium",
                            Duration = "2.5",
                            IndoorOutdoor = "Outdoor",
                            MyProperty = 0,
                            Name = "horseback riding"
                        },
                        new
                        {
                            Id = new Guid("2498dc33-6a8e-455a-8548-17e231a6c361"),
                            ActivityLevel = "High",
                            Duration = "1.5",
                            IndoorOutdoor = "Indoor",
                            MyProperty = 0,
                            Name = "boxing class"
                        },
                        new
                        {
                            Id = new Guid("3c95dde6-2d54-40cc-ae0e-e581e99ef221"),
                            ActivityLevel = "High",
                            Duration = "1.5",
                            IndoorOutdoor = "Indoor",
                            MyProperty = 0,
                            Name = "dance class"
                        },
                        new
                        {
                            Id = new Guid("ca16b378-cf25-4e8b-8fdc-8bb137555b59"),
                            ActivityLevel = "High",
                            Duration = "2",
                            IndoorOutdoor = "Indoor",
                            MyProperty = 0,
                            Name = "swing dancing"
                        },
                        new
                        {
                            Id = new Guid("b2990da4-e60f-4e42-b466-214927b583af"),
                            ActivityLevel = "High",
                            Duration = "2",
                            IndoorOutdoor = "Indoor",
                            MyProperty = 0,
                            Name = "cooking class"
                        },
                        new
                        {
                            Id = new Guid("28bd2630-21de-408d-abf7-12987037ad03"),
                            ActivityLevel = "Low",
                            Duration = "2",
                            IndoorOutdoor = "Indoor",
                            MyProperty = 0,
                            Name = "aquarium"
                        },
                        new
                        {
                            Id = new Guid("ec62a070-b65c-4d06-9a21-3ffb43dd0349"),
                            ActivityLevel = "Low",
                            Duration = "1.5",
                            IndoorOutdoor = "Indoor",
                            MyProperty = 0,
                            Name = "thrift"
                        },
                        new
                        {
                            Id = new Guid("4397ca2c-7aeb-44a6-a1ff-d13b16243117"),
                            ActivityLevel = "High",
                            Duration = "1.5",
                            IndoorOutdoor = "Indoor",
                            MyProperty = 0,
                            Name = "roller skating"
                        },
                        new
                        {
                            Id = new Guid("d5a66a77-c4ba-4edc-aec3-fce30483520d"),
                            ActivityLevel = "Low",
                            Duration = "2",
                            IndoorOutdoor = "Indoor",
                            MyProperty = 0,
                            Name = "karaoke"
                        },
                        new
                        {
                            Id = new Guid("ee7f8da9-08d4-4bac-8477-47cf4a09d5ec"),
                            ActivityLevel = "Low",
                            Duration = "1.5",
                            IndoorOutdoor = "Indoor",
                            MyProperty = 0,
                            Name = "nickelcade"
                        },
                        new
                        {
                            Id = new Guid("28974797-f54f-449a-abb5-24f6a8128a7f"),
                            ActivityLevel = "High",
                            Duration = "1.5",
                            IndoorOutdoor = "Both",
                            MyProperty = 0,
                            Name = "swimming"
                        },
                        new
                        {
                            Id = new Guid("a609ab72-edce-4942-8931-e00b25b3c125"),
                            ActivityLevel = "High",
                            Duration = "5",
                            IndoorOutdoor = "Outdoor",
                            MyProperty = 0,
                            Name = "skiing"
                        },
                        new
                        {
                            Id = new Guid("bcc161d7-e999-4442-ba79-5c63365054f0"),
                            ActivityLevel = "High",
                            Duration = "2",
                            IndoorOutdoor = "Outdoor",
                            MyProperty = 0,
                            Name = "tubing hill"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
