// <auto-generated />
using DateFinder.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DateFinder.Storage.Migrations
{
    [DbContext(typeof(DateFinderDbContext))]
    partial class DateFinderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DateFinder.Domain.Storage.Date", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Duration")
                        .HasColumnType("float");

                    b.Property<string>("IndoorOutdoor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivityLevel = "High",
                            Duration = 4.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "rock climbing"
                        },
                        new
                        {
                            Id = 2,
                            ActivityLevel = "High",
                            Duration = 2.5,
                            IndoorOutdoor = "Indoor",
                            Name = "indoor rock climbing"
                        },
                        new
                        {
                            Id = 3,
                            ActivityLevel = "Medium",
                            Duration = 5.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "amusement park"
                        },
                        new
                        {
                            Id = 4,
                            ActivityLevel = "Medium",
                            Duration = 2.0,
                            IndoorOutdoor = "Indoor",
                            Name = "bowling"
                        },
                        new
                        {
                            Id = 5,
                            ActivityLevel = "Medium",
                            Duration = 2.0,
                            IndoorOutdoor = "Any",
                            Name = "mini golf"
                        },
                        new
                        {
                            Id = 6,
                            ActivityLevel = "Medium",
                            Duration = 4.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "golf"
                        },
                        new
                        {
                            Id = 7,
                            ActivityLevel = "Medium",
                            Duration = 2.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "driving range"
                        },
                        new
                        {
                            Id = 8,
                            ActivityLevel = "High",
                            Duration = 2.0,
                            IndoorOutdoor = "Indoor",
                            Name = "trampoline park"
                        },
                        new
                        {
                            Id = 9,
                            ActivityLevel = "Low",
                            Duration = 3.5,
                            IndoorOutdoor = "Any",
                            Name = "live music"
                        },
                        new
                        {
                            Id = 10,
                            ActivityLevel = "Medium",
                            Duration = 3.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "zoo"
                        },
                        new
                        {
                            Id = 11,
                            ActivityLevel = "Medium",
                            Duration = 2.5,
                            IndoorOutdoor = "Any",
                            Name = "botanical garden"
                        },
                        new
                        {
                            Id = 12,
                            ActivityLevel = "Medium",
                            Duration = 3.0,
                            IndoorOutdoor = "Indoor",
                            Name = "museum"
                        },
                        new
                        {
                            Id = 13,
                            ActivityLevel = "Medium",
                            Duration = 2.5,
                            IndoorOutdoor = "Indoor",
                            Name = "art museum"
                        },
                        new
                        {
                            Id = 14,
                            ActivityLevel = "Medium",
                            Duration = 2.0,
                            IndoorOutdoor = "Indoor",
                            Name = "mall"
                        },
                        new
                        {
                            Id = 15,
                            ActivityLevel = "Medium",
                            Duration = 1.5,
                            IndoorOutdoor = "Indoor",
                            Name = "laser tag"
                        },
                        new
                        {
                            Id = 16,
                            ActivityLevel = "High",
                            Duration = 2.5,
                            IndoorOutdoor = "Indoor",
                            Name = "indoor scuba diving"
                        },
                        new
                        {
                            Id = 17,
                            ActivityLevel = "High",
                            Duration = 1.5,
                            IndoorOutdoor = "Indoor",
                            Name = "indoor skydiving"
                        },
                        new
                        {
                            Id = 18,
                            ActivityLevel = "Medium",
                            Duration = 2.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "ice castle"
                        },
                        new
                        {
                            Id = 19,
                            ActivityLevel = "Low",
                            Duration = 3.0,
                            IndoorOutdoor = "Indoor",
                            Name = "play/musical"
                        },
                        new
                        {
                            Id = 20,
                            ActivityLevel = "Medium",
                            Duration = 4.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "beach"
                        },
                        new
                        {
                            Id = 21,
                            ActivityLevel = "Medium",
                            Duration = 2.0,
                            IndoorOutdoor = "Indoor",
                            Name = "butterfly"
                        },
                        new
                        {
                            Id = 22,
                            ActivityLevel = "Low",
                            Duration = 1.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "farmers market"
                        },
                        new
                        {
                            Id = 23,
                            ActivityLevel = "Low",
                            Duration = 3.5,
                            IndoorOutdoor = "Indoor",
                            Name = "movie"
                        },
                        new
                        {
                            Id = 24,
                            ActivityLevel = "Low",
                            Duration = 3.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "drive in movie"
                        },
                        new
                        {
                            Id = 25,
                            ActivityLevel = "Low",
                            Duration = 1.5,
                            IndoorOutdoor = "Indoor",
                            Name = "arcade"
                        },
                        new
                        {
                            Id = 26,
                            ActivityLevel = "High",
                            Duration = 1.5,
                            IndoorOutdoor = "Any",
                            Name = "ice skating"
                        },
                        new
                        {
                            Id = 27,
                            ActivityLevel = "High",
                            Duration = 3.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "mountain biking"
                        },
                        new
                        {
                            Id = 28,
                            ActivityLevel = "Medium",
                            Duration = 1.5,
                            IndoorOutdoor = "Indoor",
                            Name = "axe throwing"
                        },
                        new
                        {
                            Id = 29,
                            ActivityLevel = "Medium",
                            Duration = 1.5,
                            IndoorOutdoor = "Any",
                            Name = "archery"
                        },
                        new
                        {
                            Id = 30,
                            ActivityLevel = "Low",
                            Duration = 1.0,
                            IndoorOutdoor = "Indoor",
                            Name = "boba"
                        },
                        new
                        {
                            Id = 31,
                            ActivityLevel = "Low",
                            Duration = 1.0,
                            IndoorOutdoor = "Indoor",
                            Name = "ice cream"
                        },
                        new
                        {
                            Id = 32,
                            ActivityLevel = "Medium",
                            Duration = 1.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "park"
                        },
                        new
                        {
                            Id = 33,
                            ActivityLevel = "Low",
                            Duration = 1.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "christmas lights"
                        },
                        new
                        {
                            Id = 34,
                            ActivityLevel = "High",
                            Duration = 1.5,
                            IndoorOutdoor = "Any",
                            Name = "pickle ball"
                        },
                        new
                        {
                            Id = 35,
                            ActivityLevel = "High",
                            Duration = 1.5,
                            IndoorOutdoor = "Indoor",
                            Name = "raquetball"
                        },
                        new
                        {
                            Id = 36,
                            ActivityLevel = "Medium",
                            Duration = 2.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "horseback riding"
                        },
                        new
                        {
                            Id = 37,
                            ActivityLevel = "High",
                            Duration = 2.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "jetskiing"
                        },
                        new
                        {
                            Id = 38,
                            ActivityLevel = "High",
                            Duration = 3.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "kayaking"
                        },
                        new
                        {
                            Id = 39,
                            ActivityLevel = "Low",
                            Duration = 5.0,
                            IndoorOutdoor = "Any",
                            Name = "road trip"
                        },
                        new
                        {
                            Id = 40,
                            ActivityLevel = "High",
                            Duration = 4.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "skiing"
                        },
                        new
                        {
                            Id = 41,
                            ActivityLevel = "High",
                            Duration = 3.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "paintballing"
                        },
                        new
                        {
                            Id = 42,
                            ActivityLevel = "High",
                            Duration = 2.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "skydiving"
                        },
                        new
                        {
                            Id = 43,
                            ActivityLevel = "Low",
                            Duration = 3.0,
                            IndoorOutdoor = "Any",
                            Name = "concert"
                        },
                        new
                        {
                            Id = 44,
                            ActivityLevel = "Medium",
                            Duration = 5.0,
                            IndoorOutdoor = "Outdoor",
                            Name = "air show"
                        },
                        new
                        {
                            Id = 45,
                            ActivityLevel = "Low",
                            Duration = 2.5,
                            IndoorOutdoor = "Indoor",
                            Name = "symphony"
                        },
                        new
                        {
                            Id = 46,
                            ActivityLevel = "High",
                            Duration = 3.5,
                            IndoorOutdoor = "Outdoor",
                            Name = "hiking"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
